#!/bin/sh

/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys
mdev -s
modprobe g_mass_storage file=/dev/mmcblk0 iSerialNumber=42 iManufacturer=Circuitco  iProduct=BeagleBone-Black

cat <<'EOF'


  _    _    _____   ____      ______   _                 _                   
 | |  | |  / ____| |  _ \    |  ____| | |               | |                  
 | |  | | | (___   | |_) |   | |__    | |   __ _   ___  | |__     ___   _ __ 
 | |  | |  \___ \  |  _ <    |  __|   | |  / _` | / __| | '_ \   / _ \ | '__|
 | |__| |  ____) | | |_) |   | |      | | | (_| | \__ \ | | | | |  __/ | |   
  \____/  |_____/  |____/    |_|      |_|  \__,_| |___/ |_| |_|  \___| |_|   


EOF

/bin/sh
